_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.9
            "6": 4.51.2
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 2
checkpoint_dir:
    value: checkpoints
data_dir:
    value: dataset/NuInsSeg
learning_rate:
    value: 0.0001
log_dir:
    value: logs
lora_alpha:
    value: 32
lora_dropout:
    value: 0.1
lora_r:
    value: 16
model_checkpoint:
    value: sam_vit_h_4b8939.pth
num_epochs:
    value: 16
num_folds:
    value: 5
num_workers:
    value: 30
random_seed:
    value: 42
val_interval:
    value: 2
